export const defaultProfessionalValue: IProfessional = {
  _id: "",
  about: null,
  workTitle: "",
  address: {
    city: "",
    locality: "",
    number: "",
    postalCode: "",
    state: "",
    street: "",
    complement: "",
  },
  avatarUrl: "",
  cellphone: "",
  email: "",
  facebookUrl: "",
  imageUrl: "",
  creditCard: {
    cardId: "",
  },
  indicatedBy: "",
  indicationExpiresIn: null,
  linkedInUrl: "",
  name: "",
  premium: false,
  recommendations: [],
  scheduleCount: 0,
  scheduleOptions: [],
  services: [],
  showAddress: true,
  theme: {
    color: "default",
    font: "font-sans",
    profile: "default",
  },
  twitterUrl: "",
  userUrl: "",
  enterpriseName: "",
  instagramUrl: "",
  externalLinks: [],
  createdAt: new Date(),
  updatedAt: new Date(),
  useEnterpriseName: false,
  whatsappPhone: "",
};
